services:

    marketing_suite.listener.kernel_response.backend_assets:
        class: numero2\MarketingSuiteBundle\EventListener\KernelResponse\BackendAssetsListener
        arguments:
            - '@contao.routing.scope_matcher'
        tags:
            - kernel.event_subscriber
